sudo: required
services:
  - docker

before_install:
  - docker build -t samsirsikar/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run samsirsikar/react-test npm test -- --coverage

after_success:
  - docker build -t samsirsikar/multi-client ./client
  - docker build -t samsirsikar/multi-nginx ./nginx
  - docker build -t samsirsikar/multi-server ./server
  - docker build -t samsirsikar/multi-worker ./worker

  #login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  #push the images to the hub
  - docker push samsirsikar/multi-client
  - docker push samsirsikar/multi-nginx
  - docker push samsirsikar/multi-server
  - docker push samsirsikar/multi-worker
